title: My Photography
email: amethujarandira552@gmail.com
description: A gallery of my photography.
baseurl: ""  
url: "https://aquacobalt.com"

theme: minima
plugins:
  - jekyll-feed

imagesurl: "/assets/galleries/"
thumbsurl: "/assets/thumbs/"